 * SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-FileCopyrightText: 2022 Unpublished <unpublished@users.noreply.github.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
name: "Validate Gradle Wrapper"

on:
  pull_request:
    branches: [ master ]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v4
      -   uses: gradle/wrapper-validation-action@v2
